### ISSUE TITLE
Default location for custom metadata should not be under `.datalad/`

### ISSUE THREAD

**Issue by mih** [datalad/datalad-revolution#103]
This will prevent changes to these file to trigger a re-aggregation of metadata, as all content underneat `.datalad/` is considered "internal" and will be ignored when determining metadata-relevant changes.

Also adjust the extractor docs accordingly.

**Comment by yarikoptic** [comment]
just for completness, you are talking about `.datalad/metadata/dataset.json` (our `DATASET_METADATA_FILE` constant), which is extracted by `datalad_core` (as in master) extractor?

Since I did not use it much (if at all) yet, I don't mind moving it.  But if/since it is datalad-specific metadata file, it is IMHO sensible to keep it under `.datalad/`. May be as `.datalad/dataset.json`?  I guess extraction should react to changes to `.datalad/` since it might have changed configuration (which extractors to use) anyways?

> will be ignored when determining metadata-relevant changes.

I guess could be solved programmatically or too difficult?

**Comment by mih** [comment]
No its not. TBH I forgot that we had that. It is about the files that the 'custom' metadata reads.

I wrote that to resolve the conceptual issue that you outlined. When someones places custom metadata in a file, it has nothing to do with datalad per se. Hence there is no reason to put it under `.datalad/` vs any other location. We simply chose (non-wisely) to single out a particular file location and have its content be able to wreak havoc with actual internal metadata structures. The switch to a dedicated 'custom' extractor prevents this problem.

This issue is about changing the default location where the 'custom' extractor looks for such files. Which BTW can now contain metadata for a dataset and also per-file metadata.

**Comment by yarikoptic** [comment]
so you fixed it by placing into `.metadata/dataset.json`.
but what is that format which lives in a generic `.metadata/dataset.json`, isn't it a "datalad" format? what if someone comes up with a standard which would also decide to keep its metadata file in such a location?  Since it is datalad-defined format, shouldn't it be at least `.metadata/datalad-dataset.json` or something like that?

**Comment by mih** [comment]
There is nothing datalad-specific about these files, including their content. The docs say:

> The content of these files must be a JSON object, and a metadata dictionary is built by updating it with the content of the JSON objects in the order in which they are given.

https://github.com/datalad/datalad-revolution/blob/master/datalad_revolution/metadata/extractors/custom.py

Moreover, the location from which these are read is configurable:
- `datalad.metadata.custom-dataset-source`
- `datalad.metadata.custom-content-source`

**Comment by mih** [comment]
Oh, and maybe you didn't see that @yarikoptic : this is all regarding the behavior of a dedicated `custom` metadata extractor that has to be explicitly enabled in order to do anything. Unintentional collision is not really an issue.

**Comment by yarikoptic** [comment]
yeah, I mixed it up with `datalad_rfc822` which is stored under `.datalad/meta.rfc822` ATM. For a generic .json metadata dump indeed `.metadata/` might be an ok location ;-) sorry for the noise.
