### ISSUE TITLE
Should  rev-create subds (without -d) add/save subds to the superds?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-revolution#97]
```
$> datalad rev-create superds
[INFO   ] Creating a new annex repo at /tmp/superds 
create(ok): /tmp/superds (dataset)                                                                                                                                              

$> cd superds

$> datalad rev-create subds  
[INFO   ] Creating a new annex repo at /tmp/superds/subds 
create(ok): /tmp/superds/subds (dataset)                                                                                                                                        

$> git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	subds/

nothing added to commit but untracked files present (use "git add" to track)

$> datalad rev-save -m "may be it saves subds?"
save(ok): . (dataset)                                                                                                                                                           

$> git status                                  
On branch master
nothing to commit, working tree clean
```
so it does.

**Comment by kyleam** [comment]
I'd guess no.  Isn't the behavior you show consistent with core's `create`?

And `rev-create`s help says:

```
The new dataset can optionally be registered in an
existing superdataset (the new dataset's path needs to be located
within the superdataset for that, and the superdataset needs to be given
explicitly via --dataset).
```

**Comment by yarikoptic** [comment]
Ok, it was "intended" and "documented" so not a bug, but a feature. But I wonder more on what is the use case we are fulfilling by allowing such created datasets not to become subdatasets automagically, especially in the realm of the revolution where everything is saved ? Thus "should ...".
And it largely boils down for me to double-semantic of using `-d` switch.

**Comment by kyleam** [comment]
> But I wonder more on what is the use case we are fulfilling by allowing such created datasets not to become subdatasets automagically

Yes, I would have interpreted this issue differently had datalad/datalad#3230 came in before this one :]

**Comment by mih** [comment]
No, because it would immediately lead to the question of "in which superdataset" and the answer to that would likely be "all the way up", which implicates that any command has to work like that, which implies a massive increase in complexity of even the simplest operations.

rev-save does behave this way, because its goal is to leave a dataset in a clean state. Which dataset? The one dataset it is operating on (or downwards with recursion, and only then).

In both cases there is never any upward modification, which I consider crucial re operational complexity.

**Comment by yarikoptic** [comment]
Isn't the answer - the one it is in, ie the one where the directory where newly created dataset belongs to (planning aside there fact that git doesn't care about empty directories)? So not the all the way up, but one directory up.

**Comment by bpoldrack** [comment]
>  But I wonder more on what is the use case we are fulfilling by allowing such created datasets not to become subdatasets automagically, especially in the realm of the revolution where everything is saved ?

Everything - well, *can be*, not *is* - saved, but it is still saved at a state, that I determine rather than some automagic. We should I not be allowed to simply create to datasets within another one and only later (if at all) add them to super? May be I want just one commit for several. Why would you insist on messing up my history? And even with `rev-save` I can have things untracked, if I decide so. The promise of simple default `rev-create`+`rev-save` was "Do whatever you want in your worktree then have one call to save the entirety (by default)". You would actually break that, by sneaking in those extra commits.

Apart from that, I don't like the idea, that we need a well defined usecase to even *allow* for simple git-like functionality. In my mind a strong reason is needed for restrictions - not the other way around!

**Comment by yarikoptic** [comment]
> Everything - well, _can be_, not _is_ - saved, but it is still saved at a state

what is not not saved 

> Why should I not be allowed to simply create two datasets within another one and only later (if at all) add them to super? May be I want just one commit for several. Why would you insist on messing up my history?

Interesting point, and I think it is just a deficiency in `create`, than anything else:  I think that your use case would be more consistently addressed if `create` allowed to be given multiple paths, hence https://github.com/datalad/datalad/issues/3233 .  Then you could create multiple subdatasets in a single command.  It would make it more consistent with all the rest of commands which do save changes to the state they introduce.  If we would start talking about "let's do something which typically saves changes in the current state, but don't save it", we still do have the `--nosave` in the `-core`:
```
$> git grep save=nosave_opt 
datalad/distribution/add.py:        save=nosave_opt,
datalad/distribution/create.py:        save=nosave_opt,
datalad/distribution/install.py:        save=nosave_opt,
datalad/distribution/remove.py:        save=nosave_opt,
datalad/interface/download_url.py:        save=nosave_opt,
datalad/metadata/aggregate.py:        save=nosave_opt,
datalad/plugin/addurls.py:        save=nosave_opt,
```
but not sure if it is even worthwhile here for a single use case of multiple subdatasets which could easily be addressed with enhancing rev-create to accept multiple paths.

> Apart from that, I don't like the idea, that we need a well defined usecase to even _allow_ for simple git-like functionality. In my mind a strong reason is needed for restrictions - not the other way around!

could you please elaborate more on this? I don't quite get what you mean

**Comment by mih** [comment]
> What I meant is that pretty much every command saves the changes to the state it introduces (remove, download-url, aggregate-metadata, extract-metadata, ...)

Sidenote: What remove does is more or less obsolete with `rev-save`, one can simply use `rm`/`os.remove`. `rev-extract-metadata` no longer modifies a dataset. I'd be very comfortable if `rev-create` would drop the ability to save in a superdataset entirely. It is typically pointless to save the state of a freshly created subdataset in the super. At any later stage `rev-save` will do the job.

**Comment by bpoldrack** [comment]
> could you please elaborate more on this? I don't quite get what you mean

I'll try: What you want here is not allowing to just create an untracked ds within another one at all (with or without `-d`). So, something that git can do our users are not allowed to. Currently you can have it both (by either using `-d` or not). You want to restrict that. Now, you want a reason to keep allowing for both ways. I think it should be the way around. You need a strong argument to disallow a `create` without adding, since pure `git`/`git-annex` can do it. There's no technical reason as far as I can tell. It's perfectly possible to have an untracked repository within another one. Your approach 

> But I wonder more on what is the use case we are fulfilling by allowing such created datasets not to become subdatasets automagically

means to restrict functionality with no other reason than "I can't imagine why a user would want that". I think we would need a reason like "this is incredibly hard to deal with for other commands and will make them pay a high price even when that situation isn't there" or "this messes up things and datalad won't work at all" or "this creates a disambiguous situation that we can't interprete".

**Comment by bpoldrack** [comment]
FTR: This is highly connected to https://github.com/datalad/datalad/issues/3230

**Comment by yarikoptic** [comment]
In the light of discussion also in https://github.com/datalad/datalad/issues/3232#issuecomment-473671367  if we talk about scopes (current directory/dataset), if you needed to create a bunch of subdatasets without saving them while creating into the dataset you are currently in, you could just change scopes while creating them to those subdataset directories. e.g.  `datalad rev-create -d subds1; datalad rev-create -d subds2` (which would move away the scope from current dataset/directory into those ones to be created) and then use rev-save to save them at once.

**Comment by bpoldrack** [comment]
Now we are talking. ;-)

Not sure yet, whether I find that particular way of allowing for it convincing, but it's a possible way to go. I think we really need to come to a conclusion in those related datalad issues before making a move here. Once we figured out how to facilitate `-d` in the future, we pretty much know how `rev-create` should behave.

**Comment by mih** [comment]
I will close this now. The command in question is no longer part of this extension and the other discussion venues are linked above.
